exercise 1

In [7]:
def n_factorial(n):
    '''
    input positive integer n and output factorial of n.

    examples:
    n_factorial(2)
    >>> 2
    n_factorial(0)
    >>> Usage: input positive integer like 1, 2, 8...
    '''
    if not isinstance(n, int) or n <= 0:
        return "Usage: input positive integer like 1, 2, 8..."
    else:
        result = 1
        for i in range(1, n + 1):
            result *= i
        return result

'Usage: input positive integer like 1, 2, 8...'

exercise 2

In [74]:
def sum_divisor(array, max_number):
    '''
    input an array and a max number, sum all divisor of the array that is below max number and output it.

    examples:
    mul_divisor([3, 7], 10)
    >>> 25
    sum_divisor([3], 10)
    >>> 18
    sum_divisor([2, 3], 10)
    >>> 32
    '''
    dict = {}
    for i in range(len(array)):
        for j in range(1, max_number):
            if j % array[i] == 0:
                dict[j] = 1
    return sum(dict)

In [73]:
sum_divisor([3, 7], 1000)

214216

In [59]:
import numpy as np
a = np.random.normal(1, 1, (3, 4))
b = np.random.normal(-1, 1, (4, 3))
a, b

(array([[0.1843474 , 0.95920098, 0.73673044, 2.74263932],
        [3.76641845, 2.39955396, 2.15366702, 0.92387579],
        [1.08674038, 0.96575619, 0.01078851, 1.22140783]]),
 array([[-3.31437472, -0.76948921, -1.25617121],
        [-2.65654727,  0.82425752,  0.02954887],
        [-0.20403958, -2.17137585, -1.82933495],
        [-1.04994641,  0.15360482, -0.51292255]]))

In [60]:
3 * a + 2 * b.T

array([[-6.07570724, -2.43549161,  1.80211216,  6.12802512],
       [ 9.76027694,  8.84717691,  2.11824935,  3.07883703],
       [ 0.74787871,  2.95636632, -3.62630437,  2.63837838]])

In [61]:
c = a @ b
c

array([[ -6.18910559,  -0.52966078,  -2.95771689],
       [-20.26730402,  -5.45487676,  -9.07401739],
       [ -7.45205587,   0.12398503,  -1.98281839]])

In [62]:
detC = np.linalg.det(c)
detC

39.22849193987964

In [63]:
invC = np.linalg.inv(c)
invC @ c # can be consider as identity matrix

array([[ 1.00000000e+00, -4.20743549e-17, -2.23091656e-16],
       [ 8.03648870e-17,  1.00000000e+00,  2.58774948e-17],
       [ 5.99223631e-16, -4.80041050e-17,  1.00000000e+00]])

In [64]:
k = np.kron(a, b)
k

array([[-6.10996362e-01, -1.41853336e-01, -2.31571897e-01,
        -3.17915147e+00, -7.38094805e-01, -1.20492065e+00,
        -2.44180076e+00, -5.66906129e-01, -9.25459573e-01,
        -9.09013441e+00, -2.11043137e+00, -3.44522455e+00],
       [-4.89727583e-01,  1.51949731e-01,  5.44725735e-03,
        -2.54816274e+00,  7.90628618e-01,  2.83433049e-02,
        -1.95715925e+00,  6.07255608e-01,  2.17695521e-02,
        -7.28595100e+00,  2.26064108e+00,  8.10418925e-02],
       [-3.76141668e-02, -4.00287493e-01, -3.37233142e-01,
        -1.95714969e-01, -2.08278584e+00, -1.75469987e+00,
        -1.50322173e-01, -1.59971870e+00, -1.34772675e+00,
        -5.59606986e-01, -5.95530079e+00, -5.01720595e+00],
       [-1.93554892e-01,  2.83166500e-02, -9.45559383e-02,
        -1.00710963e+00,  1.47337897e-01, -4.91995810e-01,
        -7.73527487e-01,  1.13165350e-01, -3.77885657e-01,
        -2.87962432e+00,  4.21282630e-01, -1.40676155e+00],
       [-1.24833221e+01, -2.89821837e+00, -4.7312664

In [65]:
b @ np.linalg.inv(b.T @ b) @ b.T

array([[ 0.73704866,  0.36000764,  0.22108706, -0.12378588],
       [ 0.36000764,  0.50711224, -0.3026911 ,  0.1694757 ],
       [ 0.22108706, -0.3026911 ,  0.81411203,  0.10407803],
       [-0.12378588,  0.1694757 ,  0.10407803,  0.94172707]])

exercise 4

In [67]:
a = np.random.rand(3,3)
a

array([[0.39056368, 0.12730915, 0.05569574],
       [0.74248228, 0.79546699, 0.65607922],
       [0.82917966, 0.78792099, 0.53721243]])

In [69]:
correlation_matrix = np.corrcoef(a, rowvar=False)
correlation_matrix

array([[1.        , 0.98054993, 0.93022684],
       [0.98054993, 1.        , 0.98416195],
       [0.93022684, 0.98416195, 1.        ]])

In [70]:
eigenvalues, eigenvectors = np.linalg.eig(correlation_matrix)
eigenvalues

array([ 2.93016603e+00,  6.98339693e-02, -1.27255862e-16])

In [71]:
sum(eigenvalues)

3.0000000000000004

In [72]:
sum(np.diagonal(correlation_matrix))

3.0

exercise 5

In [76]:
x = np.random.rand(4, 6)
x

array([[0.21065747, 0.86071513, 0.8556045 , 0.9439893 , 0.52788168,
        0.76237857],
       [0.32411953, 0.41032954, 0.40609531, 0.56173541, 0.82856347,
        0.94905884],
       [0.15782948, 0.68648004, 0.6908071 , 0.04517578, 0.77538347,
        0.04620662],
       [0.47918653, 0.48438062, 0.67966102, 0.85203327, 0.28884574,
        0.98799359]])

In [78]:
u, d, v = np.linalg.svd(x)
u, d, v

(array([[ 0.6028252 ,  0.01267379,  0.53509993, -0.59170027],
        [ 0.49369898, -0.09339765, -0.82825746, -0.24804792],
        [ 0.32525391,  0.88124716, -0.0081765 ,  0.34285052],
        [ 0.53579192, -0.46316271,  0.16610475,  0.68616072]]),
 array([2.94932622, 0.91630233, 0.5535708 , 0.23512234]),
 array([[ 0.20177017,  0.40831278,  0.44251239,  0.44674437,  0.38457565,
          0.49927277],
        [-0.12054615,  0.38545821,  0.29127237, -0.4314295 ,  0.52256364,
         -0.54115324],
        [-0.13986821,  0.35326108,  0.41318829,  0.32701229, -0.65421749,
         -0.38727428],
        [ 0.75648974, -0.18434562,  0.40918166, -0.41585044, -0.22896995,
          0.0308464 ],
        [-0.29004899, -0.71737009,  0.54866217,  0.21052455,  0.20053958,
         -0.12523915],
        [-0.5184488 ,  0.10633015,  0.28312332, -0.53860824, -0.24162972,
          0.5396871 ]]))

In [79]:
u @ u.T # can be consider as identity matrix

array([[ 1.00000000e+00,  6.06824440e-16,  2.06887739e-16,
         6.21970027e-16],
       [ 6.06824440e-16,  1.00000000e+00,  9.06137490e-17,
         2.83803303e-16],
       [ 2.06887739e-16,  9.06137490e-17,  1.00000000e+00,
        -1.74427173e-16],
       [ 6.21970027e-16,  2.83803303e-16, -1.74427173e-16,
         1.00000000e+00]])

In [80]:
v @ v.T # can be consider as identity matrix

array([[ 1.00000000e+00, -1.43257886e-16, -7.28889909e-18,
         2.47155334e-16, -3.21393059e-17, -4.82426158e-17],
       [-1.43257886e-16,  1.00000000e+00,  1.68644579e-17,
        -2.80884468e-18, -1.38112161e-16, -7.70690804e-17],
       [-7.28889909e-18,  1.68644579e-17,  1.00000000e+00,
        -5.39785833e-17, -1.21748546e-16, -1.36584390e-16],
       [ 2.47155334e-16, -2.80884468e-18, -5.39785833e-17,
         1.00000000e+00, -3.58052837e-16, -2.95139325e-17],
       [-3.21393059e-17, -1.38112161e-16, -1.21748546e-16,
        -3.58052837e-16,  1.00000000e+00, -2.70283935e-17],
       [-4.82426158e-17, -7.70690804e-17, -1.36584390e-16,
        -2.95139325e-17, -2.70283935e-17,  1.00000000e+00]])